### ISSUE TITLE
Teria uma forma mais simples de fazer esse processo de geração de token do cartão de crédito com React.js?

### ISSUE THREAD

**Issue by VladimirHybriun** [mercadopago/card-payment-sample-node#2]

**Comment by biaguerreiromeli** [comment]
@andreagostinho-meli Você saberia responder essa dúvida?

**Comment by biaguerreiromeli** [comment]
Oi, @VladimirHybriun 👋 

Nossa SDK card-payment-sample-node não suporta nativamente React, o que torna o processo mais complexo para trabalhar com a tecnologia. 

Contudo, como a SDK usa linguagem JavaScript, é possível usar React em seus métodos fazendo importações dentro da tag `<head>` do arquivo `index.html` mesmo. 

Se encontrar algum erro ao gerar tokens com React, não se esqueça do nosso canal oficial de suporte a problemas da plataforma e suas integrações: https://www.mercadopago.com/developers/pt/support/center/contact

Muito obrigada pelo seu contato!
