### ISSUE TITLE
Form Payment not working in Safari

### ISSUE THREAD

**Issue by ihojmanb** [mercadopago/card-payment-sample-node#6]
The form payment works fine in Chrome, but with Safari I cannot go through the Card details or click the Pay button. Same Problem is with the CardBrick implementation. I think it has to do with some specifications over the Content Security Policy, but I haven't been able to fix the problem. 

Any ideas?

**here's the Form in safari:**
<img width="1303" alt="image" src="https://user-images.githubusercontent.com/30912229/197622680-882d786e-9369-441b-b1a1-b0c1d0f04108.png">

**compared to the form in chrome:**
![image](https://user-images.githubusercontent.com/30912229/197623214-1ee8a673-17cc-444f-819b-3790e4d62048.png)

**Comment by andreagostinho-meli** [comment]
It is related with the usage of Secure Fields in Safari, there are problems with Content Security Policy.
I see you already mentioned this issue in the SDK JS discussion, you can follow it there: https://github.com/mercadopago/sdk-js/discussions/16

Thanks! 🙂
